export default{
    products:[
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'2',
            name:'Sports Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:6000,
            brand:'Nike',
            rating:'3.5',
            numReviews:80,
            countInStock:8,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },

    ]
}