export default{
    products:[
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'2',
            name:'Sports Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:6000,
            brand:'Nike',
            rating:'3.5',
            numReviews:80,
            countInStock:8,
        },
        {
            _id:'3',
            name:'Sports Slim Fit',
            category:'Wears',
            image:'images/product-2.jpg',
            price:4000,
            brand:'Pooma',
            rating:'5.0',
            numReviews:100,
            countInStock:60,
        },
        {
            _id:'4',
            name:'Single Rule Books',
            category:'Books',
            image:'images/product-3.jpg',
            price:100,
            brand:'Atlas',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },
        {
            _id:'4',
            name:'Samsung Phone Case',
            category:'phone',
            image:'images/product-3.jpg',
            price:1000,
            brand:'samsung',
            rating:'4.5',
            numReviews:100,
            countInStock:900,
        },
        {
            _id:'5',
            name:'Wire Mouse',
            category:'computer',
            image:'images/product-4.jpg',
            price:800,
            brand:'IBM',
            rating:'4.5',
            numReviews:100,
            countInStock:86,
        },
        {
            _id:'6',
            name:'Apple Phone Chager',
            category:'phone',
            image:'images/product-5.jpg',
            price:800,
            brand:'apple',
            rating:'4.5',
            numReviews:80,
            countInStock:60,
        },
        {
            _id:'7',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:100,
            countInStock:68,
        },
        {
            _id:'8',
            name:'Wire Mouse',
            category:'computer',
            image:'images/product-4.jpg',
            price:800,
            brand:'IBM',
            rating:'4.5',
            numReviews:100,
            countInStock:86,
        },
        {
            _id:'9',
            name:'Apple Phone Chager',
            category:'phone',
            image:'images/product-5.jpg',
            price:800,
            brand:'apple',
            rating:'4.5',
            numReviews:80,
            countInStock:60,
        },
        {
            _id:'10',
            name:'Single Rule Books',
            category:'Books',
            image:'images/product-3.jpg',
            price:100,
            brand:'Atlas',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },
        {
            _id:'11',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'12',
            name:'Single Rule Books',
            category:'Books',
            image:'images/product-3.jpg',
            price:100,
            brand:'Atlas',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },
        {
            _id:'13',
            name:'Square Rule Books',
            category:'Books',
            image:'images/product-4.jpg',
            price:102,
            brand:'Atlas',
            rating:'2.5',
            numReviews:100,
            countInStock:9000,
        },
        {
            _id:'14',
            name:'Full Zip Running Shirts',
            category:'Shirts',
            image:'images/product-1.jpg',
            price:600,
            brand:'Nike',
            rating:'4.5',
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'15',
            name:'Single Rule Books',
            category:'Books',
            image:'images/product-3.jpg',
            price:100,
            brand:'Atlas',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },
        {
            _id:'16',
            name:'Apple Phone Chager',
            category:'phone',
            image:'images/product-5.jpg',
            price:800,
            brand:'apple',
            rating:'4.5',
            numReviews:80,
            countInStock:60,
        },
        {
            _id:'17',
            name:'Single Rule Books',
            category:'Books',
            image:'images/product-5.jpg',
            price:100,
            brand:'Atlas',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },
        {
            _id:'18',
            name:'Apple Rule Books',
            category:'phoen',
            image:'images/product-6.jpg',
            price:1000,
            brand:'Apple',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },

        {
            _id:'19',
            name:'Laptop Screens',
            category:'laptop',
            image:'images/product-1.jpg',
            price:1000,
            brand:'laptop',
            rating:'4.5',
            numReviews:1000,
            countInStock:5000,
        },

    ]
}